# Start from base image
FROM fredmanglis/guix-conda-plain:latest

# Configure channels for bioconda
RUN /opt/gnu/bin/conda config --add channels r
RUN /opt/gnu/bin/conda config --add channels defaults
RUN /opt/gnu/bin/conda config --add channels conda-forge
RUN /opt/gnu/bin/conda config --add channels bioconda
